### ISSUE TITLE
Dependency issues in registering wcUnique directive

### ISSUE THREAD

**Issue by sasikumardr** [DanWahlin/AngularTypeScriptExpenseManager#9]
wcUnique Directive registration in the file wcUnique.directive.ts will have dependency Injection issues when we started using that directive.

I have simulated this issue in typescript and used resulting javascript in plunker. We can see dependency injection error in console.

typescript implementation of directive similar to this in [playground](http://www.typescriptlang.org/Playground#src=angular.module%28'test'%2C%20%5B'first'%5D%29%3B%0Anamespace%20first%20%7B%0A%09class%20TestDirective%20implements%20angular.IDirective%20%7B%0A%09%09restrict%20%3D%20'E'%3B%0A%09%09template%20%3D%20'%3Ch1%3Ewelcome%3C%2Fh1%3E'%3B%0A%09%09%0A%09%09static%20%24inject%20%3D%20%5B'service'%5D%3B%0A%09%09static%20instance%28TestService%3A%20first.ITestService%29%20%7B%0A%09%09%09return%20new%20TestDirective%28TestService%29%3B%0A%09%09%7D%0A%09%09constructor%28private%20TestService%3A%20first.ITestService%29%20%7B%0A%09%09%09if%28TestService.test%28%29%29%0A%09%09%09%09console.log%28'Success'%29%3B%0A%09%09%7D%0A%09%7D%0A%09angular.module%28'first'%2C%20%5B%5D%29.directive%28'test'%2C%20TestDirective.instance%29%3B%0A%7D%0A%0Anamespace%20first%20%7B%0A%09export%20interface%20ITestService%20%7B%0A%09%09test%28%29%20%3Aboolean%3B%0A%09%7D%0A%09%0A%09class%20TestService%20implements%20ITestService%20%7B%0A%09%09constructor%28%29%20%7B%7D%0A%09%09%0A%09%09test%28%29%3A%20boolean%20%7B%0A%09%09%09return%20true%3B%0A%09%09%7D%0A%09%7D%0A%09%0A%09angular.module%28'first'%29.service%28'service'%2C%20TestService%29%3B%0A%7D)

using javascript in plunkr: http://plnkr.co/edit/nKB36UZH6aLfjhYSbKts

**Comment by DanWahlin** [comment]
It's currently being used in the app successfully (no injection issues). Are you unable to run it in the app for this project?

**Comment by DanWahlin** [comment]
Just realized the sample you have isn't exactly the same as the directive code. The static $inject isn't actually being used (I need to remove that). This is how the directive is defined at the bottom of the file:

wcDirectivesApp.directive('wcOverlay', ['$q', '$timeout', '$window', 'httpInterceptor', OverlayDirective.instance]);

Your sample doesn't use that which is why you're getting injection issues. If you change the sample to this it works:

angular.module('first', []).directive('test', ['service', TestDirective.instance]);

**Comment by sasikumardr** [comment]
actually I am not able to find out where exactly this is used. I did a quick search in repo (searchbar at top) and found that only 2 files have text 'wcUnique' - wcUnique.directive.ts  and index.html (just including script here).

I am now working on a angular typescript application, and I tried to used similar implementation as given in this directive. But I am getting serviceprovider injection error. If we inject service while registering directive, everything is fine

**Comment by DanWahlin** [comment]
Very bottom of the file is where the injection occurs (when the directive is added into Angular): https://github.com/DanWahlin/AngularTypeScriptExpenseManager/blob/master/src/public/app/wc.directives/directives/wcOverlay.directive.ts

Without that the injection problem occurs especially when the names of the function parameters don't match exactly with the actual service names.

**Comment by DanWahlin** [comment]
Well - shoot. Just realized you're talking about wcUnique. :-) My bad. Let me look at that one...guessing it just needs what I mention above.

**Comment by sasikumardr** [comment]
Overlay is working fine. I was referring wcUnique directive inside expenseApp folder.

And Yes static $inject does not do anything here. But I found another implementation - http://blog.aaronholmes.net/writing-angularjs-directives-as-typescript-classes/#backtothebasics . this makes use of $inject and does not require DI while registering directive. Also I think if we use this all DI would be consistent (like controller, service)

I have tested that method and working fine

**Comment by DanWahlin** [comment]
Looks like wcOverlay (the one I was referring to) is correct but wcUnique doesn't have that. It should be:

angular.module('expenseApp').directive('wcUnique', ['$q', 'expenseApp.services.DataService', WcUniqueDirective.instance]);

I'll get it updated.

**Comment by DanWahlin** [comment]
Thanks for the link. I'll take a look at that when I get some time.

**Comment by sasikumardr** [comment]
okay :+1: Its just small tweak in that static instant function. 2-3 lines extra. our static instance function given as static Factory in above link.

**Comment by DanWahlin** [comment]
Just updated the wcUnique to inject things properly. Thanks for pointing that out (I'll also be looking at the other approach).
